database:
  dbname: batch3dfier_db
  host: localhost
  port: 5432
  user: batch3dfier
  pw:

input_polygons:
  footprints:
    schema: bagactueel
    table: pandactueelbestaand
    fields:
      primary_key: gid
      geometry: geom
      uniqueid: identificatie
  tile_schema: bag_tiles
  user_schema:
  tile_prefix: t_
  extent: /home/bdukai/Development/batch3dfier/example_data/extent_small.geojson
  tile_list: [25gn1_c1, 25gn1_c2, 25gn1_c3, 25gn1_c4]

input_elevation:
  dataset_dir:
    - /example_data/ahn3
    - /example_data/ahn2/merged
  dataset_name:
    - "C_{tile}.LAZ"
    - "{tile}.laz"

quality:
  ahn2_rast_dir: /data/raster/AHN2
  ahn3_rast_dir: /data/raster/AHN3
  results: /data/3DBAG/quality/ahn_rast.csv
  sample_size: 10.0

tile_index:
  polygons:
    schema: tile_index
    table: bag_index_test
    fields:
      primary_key: id
      geometry: geom
      unit_name: bladnr
    file: example_data/bag_index_test.json
  elevation:
    schema: tile_index
    table: ahn_index
    border_table: border_tiles
    fields:
      primary_key: id
      geometry: geom
      unit_name: bladnr
      version: ahn_version
    file: example_data/ahn_index.json
  identical: True

output:
  staging:
    dir: /tmp/3DBAG_staging
    schema: 3dbag_staging
    heights_table: heights
    bag3d_table: pand3d
  production:
    dir: /tmp/3DBAG
    schema: 3dbag_production
    bag3d_table: pand3d

path_3dfier: /home/bdukai/Development/3dfier/build/3dfier
path_lasinfo: /usr/local/bin/lasinfo


